config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#show'
  get 'auth/:provider/callback', to: 'users/sessions#create'
  get 'log_out', to: 'users/sessions#destroy'
  get 'auth/failure', to: 'users/sessions#failure'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
# frozen_string_literal: true

class Challenge < ApplicationRecord
  has_one_attached :image

  validates :points, :title, presence: true

  validates :points, numericality: { greater_than_or_equal_to: 1 }
end

app/models/completed_challenge.rb
# frozen_string_literal: true

class CompletedChallenge < ApplicationRecord
  has_many_attached :proof

  belongs_to :team
  belongs_to :user
  belongs_to :challenge
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  validates :title, :number_of_teams, :players_per_team, :start_datetime, :end_datetime, presence: true

  validates :number_of_teams, :players_per_team, numericality: { greater_than_or_equal_to: 1 }

  validate :instance_is_singleton, :order_of_start_and_stop_date

  with_options dependent: :destroy do
    has_many :challenges
    has_many :teams
  end

  with_options dependent: :nullify do
    has_one :rule, class_name: 'rules'
    has_many :users, through: :teams
  end

  after_commit { Rails.cache.delete('game_instance') }

  def self.instance
    Rails.cache.fetch('game_instance') { all.first }
  end

  def instance_is_singleton
    singleton = Game.all.first
    errors.add(:base, I18n.t('game.too_many')) if self != singleton && !singleton.nil?
  end

  def order_of_start_and_stop_date
    errors.add(:base, I18n.t('game.date_mismatch')) unless start_datetime < end_datetime
  end
end

app/models/rule.rb
# frozen_string_literal: true

class Rule < ApplicationRecord
  has_rich_text :content

  belongs_to :game
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  has_one_attached :logo
  has_one_attached :banner

  validates :name, presence: true

  with_options dependent: :nullify do
    has_many :users
    has_many :completed_challenges, through: :users
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }

  with_options dependent: :destroy do
    has_many :completed_challenges
  end

  def self.from_omniauth(auth)
    find_or_create_by(email: auth.info.email) do |user|
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.provider = auth.provider
      user.uid = auth.uid
    end
  end
end

app/models/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:create]

    def create
      user = User.from_omniauth(request.env['omniauth.auth'])

      if user.persisted?
        session[:user_id] = user.id

        redirect_to root_url, notice: 'You have signed in successfully!'
      else
        redirect_to root_url, alert: 'There was a problem signing you in, please try again.'
      end
    end

    def destroy
      session[:user_id] = nil

      redirect_to root_url, notice: 'You have signed out successfully!'
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Authentication

  before_action :authenticate_user!

  def authenticate_user!
    return if Current.user

    redirect_to root_path, alert: 'You need to sign in before continuing.'
  end
end

app/controllers/concerns/authentication.rb
# frozen_string_literal: true

module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :authenticate
  end

  def clear_session
    session[:user_id] = nil
  end

  private

  def authenticate
    authenticated_user = User.find_by(id: session[:user_id])

    return unless authenticated_user

    Current.user = authenticated_user
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/show.html.erb
<div class="container text-center mt-5">
  <h2 id="countdown" class="mb-5">Countdown placeholder</h2>

  <div class="embed-responsive embed-responsive-16by9 mb-5">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/your_youtube_video_id" allowfullscreen></iframe>
  </div>

  <div class="social-links mb-5">
    <a href="#" class="btn btn-secondary">Discord</a>
    <a href="#" class="btn btn-secondary">Twitter</a>
    <a href="#" class="btn btn-secondary">Game Rules</a>
  </div>

  <div class="prizes">
    <h3 class="mb-3">First Place Prize: ...</h3>
    <h3 class="mb-3">Second Place Prize: ...</h3>
    <h3 class="mb-3">Third Place Prize: ...</h3>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OsrsBingo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-dark text-warning">
    <nav class="navbar navbar-expand-lg navbar-dark bg-gray fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Bingo</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/standings">Current Standings</a>
            </li>
          </ul>
          <ul class="navbar-nav align-items-center">
            <% if Current.user %>
              <li class="nav-item">
                <span class="navbar-text me-3">Hi <%= Current.user.first_name %></span>
                <li class="nav-item">
                  <%= link_to "Log Out", log_out_path, class: "nav-link" %>
                </li>
              </li>
            <% else %>
              <li class="nav-item">
                <%= button_to "Sign In / Sign Up", "/auth/google_oidc", data: { turbo: false }, class: "btn btn-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

  </body>
</html>